---
title: "medicaid_final"
author: "Anton Hung"
date: "2024-03-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(arrow)
library(tidyverse)
library(lubridate)
library(data.table)
library(furrr)
library(tidylog)
library(tictoc)
library(doFuture)

load_dir <- "/mnt/general-data/disability/create_cohort/"
```
# Load data
```{r}
cohort <- readRDS(paste0(load_dir, "final/analysis_cohort.rds"))
setDT(cohort)

cohort <- cohort[, c("BENE_ID",
                     "washout_start_dt",
                     "washout_12mos_end_dt",
                     "dem_race_cond",
                     "disability_pain_12mos_cal",
                     "opioid_pain_washout_12mos_cal"
                     )]
head(cohort)
```

# MME
```{r}
all_opioids_clean <- readRDS(paste0("/mnt/general-data/disability/mediation_unsafe_pain_mgmt/all_pain_opioids.rds"))

setDT(all_opioids_clean)
setkey(all_opioids_clean, BENE_ID)
all_opioids_clean <- all_opioids_clean[, .(BENE_ID, NDC, opioid, mme_strength_per_day, rx_start_dt, rx_end_dt)]

# Merge to the analysis cohort
all_opioids_clean_merged <- merge(all_opioids_clean, cohort, by = "BENE_ID")

# Filter opioid prescriptions to only contain those within mediator period
all_opioids_clean_mediator_period <- all_opioids_clean_merged[
  all_opioids_clean_merged$rx_start_dt %within% interval(
    all_opioids_clean_merged$washout_start_dt, all_opioids_clean_merged$washout_12mos_end_dt
  ), 
]

# Calculate monthly MME dose -----------------------------------------------------

# Group by beneficiary and create a list column containing each beneficiairy's data
opioids <- all_opioids_clean_mediator_period[, list(data = list(data.table(.SD))), by = BENE_ID]

# Create function
calculate_monthly_dose <- function(data) {
  to_modify <- copy(data)
  
  # Calculate the date limit based on washout_cal_end_dt + 182 days
  washout_date_limit <- to_modify$washout_12mos_end_dt #+ lubridate::days(182)
  
  long <- to_modify[, .(date = seq(rx_start_dt, rx_end_dt, by = "1 day"), 
                        NDC, opioid, mme_strength_per_day), by = .(seq_len(nrow(data)))
  ][date <= washout_date_limit, ]  # Filter rows based on date limit
  
  long[, .(total_mme_strength = sum(mme_strength_per_day, na.rm = TRUE))
  ][, .(mediator_monthly_dose_mme = total_mme_strength/12)]
}

plan(multisession, workers = 50)

# Apply function
out <- foreach(data = opioids$data, 
               id = opioids$BENE_ID, 
               .combine = "rbind",
               .options.future = list(chunk.size = 1e4)) %dofuture% {
                 out <- calculate_monthly_dose(data)
                 out$BENE_ID <- id
                 setcolorder(out, "BENE_ID")
                 out
               }

plan(sequential)

save_dir <- "/home/amh2389/medicaid"
saveRDS(out, file.path(save_dir, "mediator_monthly_dose_mme.rds"))
```

# Merge intermediates

```{r}
out <- readRDS(file.path(save_dir, "mediator_monthly_dose_mme.rds"))

# Right join with cohort
cohort <- merge(out, cohort, all.y = TRUE, by = "BENE_ID")

# Convert NAs to 0 for observations in the cohort that didn't have a claim
cohort[, mediator_monthly_dose_mme := fifelse(is.na(mediator_monthly_dose_mme), 0, mediator_monthly_dose_mme)]
```

# Days covered

## Preparing the otl and rxl data
```{r}
otl <- readRDS("/mnt/general-data/disability/mediation_unsafe_pain_mgmt/otl_opioids_pain_mme.rds")
rxl <- readRDS("/mnt/general-data/disability/mediation_unsafe_pain_mgmt/rxl_opioids_pain_mme.rds")

cohort_12mos_end_date <- cohort[, c("BENE_ID", "washout_start_dt", "washout_12mos_end_dt")]
otl <- as.data.table(otl)
otl <- merge(otl, cohort_12mos_end_date, "BENE_ID")
otl <- otl[LINE_SRVC_BGN_DT %within% interval(washout_start_dt, 
                                              washout_12mos_end_dt), 
           .(BENE_ID, CLM_ID, LINE_SRVC_BGN_DT, washout_start_dt, washout_12mos_end_dt, NDC, NDC_QTY, 
             flag_opioid_analgesic, flag_opioid_anesthetics)]


rxl <- as.data.table(rxl)
rxl <- merge(rxl, cohort_12mos_end_date, "BENE_ID")
rxl <- rxl[RX_FILL_DT %within% interval(washout_start_dt, 
                                        washout_12mos_end_dt), 
           .(BENE_ID, CLM_ID, RX_FILL_DT, washout_start_dt, washout_12mos_end_dt, NDC, NDC_QTY, DAYS_SUPPLY,
             flag_opioid_analgesic, flag_opioid_anesthetics)]

```

## Calculating proportion of days covered
```{r}
prop_days_covered <- function(data) {
    dur <- 0
    current_int <- data$rx_int[1]
    for (i in 1:nrow(data)) {
        check <- intersect(current_int, data$rx_int[i + 1])
        if (is.na(check)) {
            # if they don't intersect, add the duration of the first interval
            dur <- dur + as.duration(current_int)
            current_int <- data$rx_int[i + 1]
        } else {
            # if they do intersect, then update current interval as the union
            current_int <- union(current_int, data$rx_int[i + 1])
        }
    }

    max(time_length(dur, "days") / 365, 1 / 365)
}
# prop_days_covered_rolling <- function(data, window_size = 6) {
#     total_days_covered <- 0
#     total_intervals <- 0
#     
#     for (i in 1:(nrow(data) - window_size + 1)) {
#         current_window <- data$rx_int[i:(i + window_size - 1)]
#         combined_intervals <- current_window[[1]]
#         
#         for (j in 2:length(current_window)) {
#             combined_intervals <- union(combined_intervals, current_window[[j]])
#         }
#         
#         total_days_covered <- total_days_covered + time_length(as.duration(combined_intervals), "days")
#         total_intervals <- total_intervals + 1
#     }
#     
#     avg_days_covered <- total_days_covered / total_intervals
#     max(time_length(avg_days_covered, "days") / 182, 1 / 182)
# 
# }


opioids <- otl |> 
    mutate(rx_int = interval(LINE_SRVC_BGN_DT, LINE_SRVC_BGN_DT + days(1)), 
           rx_int = intersect(rx_int, interval(washout_start_dt, 
                                               washout_12mos_end_dt))) |> 
    select(BENE_ID, rx_int) |> 
    as_tibble() |> 
    bind_rows({
        rxl |> 
            mutate(DAYS_SUPPLY = replace_na(DAYS_SUPPLY, 1), 
                   rx_int = interval(RX_FILL_DT, RX_FILL_DT + days(DAYS_SUPPLY)), 
                   rx_int = intersect(rx_int, interval(washout_start_dt, 
                                                       washout_12mos_end_dt))) |> 
            select(BENE_ID, rx_int) |> 
            as_tibble()
    })

opioids <- group_by(opioids, BENE_ID) |> 
    arrange(BENE_ID, int_start(rx_int)) |> 
    nest()

plan(multisession, workers = 50)

opioids$mediator_opioid_days_covered <- 
    foreach(x = opioids$data,
            .combine = "c",
            .options.future = list(chunk.size = 1e4)) %dofuture% {
                prop_days_covered(x)
            }





```

```{r}
opioids2 <- opioids[, c("BENE_ID", "mediator_opioid_days_covered")]
saveRDS(opioids2, file.path(save_dir, "mediator_opioid_days_covered.rds"))
opioids <- readRDS(file.path(save_dir, "mediator_opioid_days_covered.rds"))

plan(sequential)

opioids <- select(cohort, BENE_ID) |>
    left_join(select(opioids, -data)) |>
    mutate(mediator_opioid_days_covered = replace_na(mediator_opioid_days_covered, 0))


cohort <- merge(opioids, cohort, all.y = TRUE, by = "BENE_ID")
```


# Results
```{r}
setDT(cohort)
my_func <- function(data, which_race, which_year, which_pain_or_disability) {
  subset <- data[dem_race_cond == which_race &
    year(washout_start_dt) == which_year &
    disability_pain_12mos_cal == which_pain_or_disability]

  num_bene <- nrow(subset)

  # subsetting down to just those who were prescribed an opioid during washout
  subset <- subset[opioid_pain_washout_12mos_cal == 1]
  
  opioid_proba <- round(nrow(subset)/num_bene, 3)
  se_opioid_proba <- round(sqrt((opioid_proba * (1-opioid_proba))/num_bene),3)
  
  average_mme <- round(mean(subset$mediator_monthly_dose_mme, na.rm=T),3)
  se_mme <- round(sd(subset$mediator_monthly_dose_mme, na.rm=T)/sqrt(num_bene),3)
    
  average_days_covered <- round(mean(subset$mediator_opioid_days_covered, na.rm=T),3)
  se_days_covered <- round(sd(subset$mediator_opioid_days_covered, na.rm=T)/sqrt(num_bene),3)
  

  return(c(which_race, 
           which_year, 
           which_pain_or_disability,
           num_bene,
           opioid_proba,
           se_opioid_proba,
           average_mme,
           se_mme,
           average_days_covered,
           se_days_covered
           ))
}

results <- data.frame()

for (i in c("multi_or_na", 
            "White, non-Hispanic", 
            "Black, non-Hispanic", 
            "Hispanic, all races", 
            "AIAN_or_HPI",
            "Asian, non-Hispanic")) {
  for (j in 2016:2019) {
    for (k in c("disability only", "chronic pain only", "neither", "disability and chronic pain")){
      results <- rbind(results, my_func(cohort, i, j, k))
      
    }
  }
}

colnames(results) <- c("race_ethnicity",
                       "year",
                       "pain_or_disability",
                       "number_of_beneficiaries",
                       "opioid_prop",
                       "se_opioid_prop",
                       "average_mme",
                       "se_mme",
                       "average_days_covered",
                       "se_days_covered")

results[, -c(1,3)] <- lapply(results[, -c(1,3)], as.numeric)

saveRDS(results, file.path(save_dir, "results_df3.rds"))
# results <- readRDS(file.path(drv_root, "results_df3.rds"))

results
```


# Plots
```{r}
library(ggplot2)

p <- ggplot(results, aes(x = year, y=opioid_prop, color = race_ethnicity)) +
  geom_jitter(position=position_dodge(0.2)) +
  geom_line(aes(group = race_ethnicity), position=position_dodge(0.2)) +
  # geom_smooth()+
  ggtitle("Proportion of beneficiaries who were prescribed an opioid, by pain/disability status, race/ethnicity, and year") +
  ylab("Proportion") +
  facet_wrap(~factor(pain_or_disability, levels = c("chronic pain only","disability only","disability and chronic pain","neither"))) +
  geom_errorbar(aes(ymin = opioid_prop - 1.96*se_opioid_prop, 
                    ymax = opioid_prop + 1.96*se_opioid_prop),
                width = 1, position = position_dodge(0.2))
p
# ggsave(file = file.path(save_dir, "plots", "opioid_prop.pdf"), width = 10, height = 7)
```


```{r}
p <- ggplot(results, aes(x = year, y=average_mme, color = race_ethnicity)) +
  geom_jitter(position=position_dodge(0.2)) +
  geom_line(aes(group = race_ethnicity), position=position_dodge(0.2)) +
  ggtitle("Average MME per month, by pain/disability status, race/ethnicity, and year") +
  ylab("MME per month") +
  facet_wrap(~factor(pain_or_disability, levels = c("chronic pain only","disability only","disability and chronic pain","neither"))) +
  geom_errorbar(aes(ymin = average_mme - 1.96*se_mme, 
                    ymax = average_mme + 1.96*se_mme),
                width = 1, position = position_dodge(0.2))
p
ggsave(file = file.path(save_dir, "plots", "average_mme.pdf"), width = 10, height = 7)
```



```{r}
p <- ggplot(results, aes(x = year, y=average_days_covered, color = race_ethnicity)) +
  geom_jitter(position=position_dodge(0.2)) +
  geom_line(aes(group = race_ethnicity), position=position_dodge(0.2)) +
  ggtitle("Average proportion of days covered over 12-month span, by pain/disability status, race/ethnicity, and year") +
  ylab("Proportion days covered") +
  facet_wrap(~factor(pain_or_disability, levels = c("chronic pain only","disability only","disability and chronic pain","neither"))) +
  geom_errorbar(aes(ymin = average_days_covered - 1.96*se_days_covered, 
                    ymax = average_days_covered + 1.96*se_days_covered),
                width = 1, position = position_dodge(0.2))
p
ggsave(file = file.path(save_dir, "plots", "average_days_covered.pdf"), width = 10, height = 7)
```
